# Generated by Django 6.0.1 on 2026-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_category_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('INR', 'INR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Exchange rate used at time of transaction.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in the selected currency (before conversion).', max_digits=15, null=True),
        ),
    ]
