/// All supported fiat currencies: code → (name, symbol)
const fiatCurrencies = <String, (String, String)>{
  'AED': ('UAE Dirham', 'د.إ'),
  'AFN': ('Afghan Afghani', '؋'),
  'ALL': ('Albanian Lek', 'L'),
  'AMD': ('Armenian Dram', '֏'),
  'ANG': ('Netherlands Antillean Guilder', 'ƒ'),
  'AOA': ('Angolan Kwanza', 'Kz'),
  'ARS': ('Argentine Peso', '\$'),
  'AUD': ('Australian Dollar', 'A\$'),
  'AWG': ('Aruban Florin', 'ƒ'),
  'AZN': ('Azerbaijani Manat', '₼'),
  'BAM': ('Bosnia-Herzegovina Mark', 'KM'),
  'BBD': ('Barbadian Dollar', '\$'),
  'BDT': ('Bangladeshi Taka', '৳'),
  'BGN': ('Bulgarian Lev', 'лв'),
  'BHD': ('Bahraini Dinar', '.د.ب'),
  'BIF': ('Burundian Franc', 'FBu'),
  'BMD': ('Bermudian Dollar', '\$'),
  'BND': ('Brunei Dollar', '\$'),
  'BOB': ('Bolivian Boliviano', 'Bs.'),
  'BRL': ('Brazilian Real', 'R\$'),
  'BSD': ('Bahamian Dollar', '\$'),
  'BTN': ('Bhutanese Ngultrum', 'Nu.'),
  'BWP': ('Botswanan Pula', 'P'),
  'BYN': ('Belarusian Ruble', 'Br'),
  'BZD': ('Belize Dollar', 'BZ\$'),
  'CAD': ('Canadian Dollar', 'C\$'),
  'CDF': ('Congolese Franc', 'FC'),
  'CHF': ('Swiss Franc', 'CHF'),
  'CLP': ('Chilean Peso', '\$'),
  'CNY': ('Chinese Yuan', '¥'),
  'COP': ('Colombian Peso', '\$'),
  'CRC': ('Costa Rican Colon', '₡'),
  'CUC': ('Cuban Convertible Peso', '\$'),
  'CUP': ('Cuban Peso', '₱'),
  'CVE': ('Cape Verdean Escudo', '\$'),
  'CZK': ('Czech Koruna', 'Kč'),
  'DJF': ('Djiboutian Franc', 'Fdj'),
  'DKK': ('Danish Krone', 'kr'),
  'DOP': ('Dominican Peso', 'RD\$'),
  'DZD': ('Algerian Dinar', 'د.ج'),
  'EGP': ('Egyptian Pound', 'E£'),
  'ERN': ('Eritrean Nakfa', 'Nfk'),
  'ETB': ('Ethiopian Birr', 'Br'),
  'EUR': ('Euro', '€'),
  'FJD': ('Fijian Dollar', 'FJ\$'),
  'FKP': ('Falkland Islands Pound', '£'),
  'GBP': ('British Pound', '£'),
  'GEL': ('Georgian Lari', '₾'),
  'GHS': ('Ghanaian Cedi', 'GH₵'),
  'GIP': ('Gibraltar Pound', '£'),
  'GMD': ('Gambian Dalasi', 'D'),
  'GNF': ('Guinean Franc', 'FG'),
  'GTQ': ('Guatemalan Quetzal', 'Q'),
  'GYD': ('Guyanaese Dollar', '\$'),
  'HKD': ('Hong Kong Dollar', 'HK\$'),
  'HNL': ('Honduran Lempira', 'L'),
  'HTG': ('Haitian Gourde', 'G'),
  'HUF': ('Hungarian Forint', 'Ft'),
  'IDR': ('Indonesian Rupiah', 'Rp'),
  'ILS': ('Israeli New Shekel', '₪'),
  'INR': ('Indian Rupee', '₹'),
  'IQD': ('Iraqi Dinar', 'ع.د'),
  'IRR': ('Iranian Rial', '﷼'),
  'ISK': ('Icelandic Krona', 'kr'),
  'JMD': ('Jamaican Dollar', 'J\$'),
  'JOD': ('Jordanian Dinar', 'JD'),
  'JPY': ('Japanese Yen', '¥'),
  'KES': ('Kenyan Shilling', 'KSh'),
  'KGS': ('Kyrgystani Som', 'сом'),
  'KHR': ('Cambodian Riel', '៛'),
  'KMF': ('Comorian Franc', 'CF'),
  'KPW': ('North Korean Won', '₩'),
  'KRW': ('South Korean Won', '₩'),
  'KWD': ('Kuwaiti Dinar', 'د.ك'),
  'KYD': ('Cayman Islands Dollar', '\$'),
  'KZT': ('Kazakhstani Tenge', '₸'),
  'LAK': ('Laotian Kip', '₭'),
  'LBP': ('Lebanese Pound', 'L£'),
  'LKR': ('Sri Lankan Rupee', 'Rs'),
  'LRD': ('Liberian Dollar', '\$'),
  'LSL': ('Lesotho Loti', 'L'),
  'LYD': ('Libyan Dinar', 'ل.د'),
  'MAD': ('Moroccan Dirham', 'MAD'),
  'MDL': ('Moldovan Leu', 'L'),
  'MGA': ('Malagasy Ariary', 'Ar'),
  'MKD': ('Macedonian Denar', 'ден'),
  'MMK': ('Myanmar Kyat', 'K'),
  'MNT': ('Mongolian Tugrik', '₮'),
  'MOP': ('Macanese Pataca', 'MOP\$'),
  'MRU': ('Mauritanian Ouguiya', 'UM'),
  'MUR': ('Mauritian Rupee', '₨'),
  'MVR': ('Maldivian Rufiyaa', 'Rf'),
  'MWK': ('Malawian Kwacha', 'MK'),
  'MXN': ('Mexican Peso', 'MX\$'),
  'MYR': ('Malaysian Ringgit', 'RM'),
  'MZN': ('Mozambican Metical', 'MT'),
  'NAD': ('Namibian Dollar', 'N\$'),
  'NGN': ('Nigerian Naira', '₦'),
  'NIO': ('Nicaraguan Cordoba', 'C\$'),
  'NOK': ('Norwegian Krone', 'kr'),
  'NPR': ('Nepalese Rupee', '₨'),
  'NZD': ('New Zealand Dollar', 'NZ\$'),
  'OMR': ('Omani Rial', '﷼'),
  'PAB': ('Panamanian Balboa', 'B/.'),
  'PEN': ('Peruvian Sol', 'S/.'),
  'PGK': ('Papua New Guinean Kina', 'K'),
  'PHP': ('Philippine Peso', '₱'),
  'PKR': ('Pakistani Rupee', '₨'),
  'PLN': ('Polish Zloty', 'zł'),
  'PYG': ('Paraguayan Guarani', '₲'),
  'QAR': ('Qatari Riyal', '﷼'),
  'RON': ('Romanian Leu', 'lei'),
  'RSD': ('Serbian Dinar', 'din.'),
  'RUB': ('Russian Ruble', '₽'),
  'RWF': ('Rwandan Franc', 'RF'),
  'SAR': ('Saudi Riyal', '﷼'),
  'SBD': ('Solomon Islands Dollar', 'SI\$'),
  'SCR': ('Seychellois Rupee', '₨'),
  'SDG': ('Sudanese Pound', 'SDG'),
  'SEK': ('Swedish Krona', 'kr'),
  'SGD': ('Singapore Dollar', 'S\$'),
  'SHP': ('Saint Helena Pound', '£'),
  'SLE': ('Sierra Leonean Leone', 'Le'),
  'SLL': ('Sierra Leonean Leone (old)', 'Le'),
  'SOS': ('Somali Shilling', 'Sh'),
  'SRD': ('Surinamese Dollar', '\$'),
  'SSP': ('South Sudanese Pound', '£'),
  'STN': ('Sao Tome and Principe Dobra', 'Db'),
  'SVC': ('Salvadoran Colon', '₡'),
  'SYP': ('Syrian Pound', '£'),
  'SZL': ('Swazi Lilangeni', 'E'),
  'THB': ('Thai Baht', '฿'),
  'TJS': ('Tajikistani Somoni', 'SM'),
  'TMT': ('Turkmenistani Manat', 'T'),
  'TND': ('Tunisian Dinar', 'د.ت'),
  'TOP': ('Tongan Paanga', 'T\$'),
  'TRY': ('Turkish Lira', '₺'),
  'TTD': ('Trinidad & Tobago Dollar', 'TT\$'),
  'TWD': ('New Taiwan Dollar', 'NT\$'),
  'TZS': ('Tanzanian Shilling', 'TSh'),
  'UAH': ('Ukrainian Hryvnia', '₴'),
  'UGX': ('Ugandan Shilling', 'USh'),
  'USD': ('US Dollar', '\$'),
  'UYU': ('Uruguayan Peso', '\$U'),
  'UZS': ('Uzbekistani Som', 'сўм'),
  'VES': ('Venezuelan Bolivar', 'Bs.S'),
  'VND': ('Vietnamese Dong', '₫'),
  'VUV': ('Vanuatu Vatu', 'VT'),
  'WST': ('Samoan Tala', 'WS\$'),
  'XAF': ('Central African CFA Franc', 'FCFA'),
  'XCD': ('East Caribbean Dollar', 'EC\$'),
  'XOF': ('West African CFA Franc', 'CFA'),
  'XPF': ('CFP Franc', '₣'),
  'YER': ('Yemeni Rial', '﷼'),
  'ZAR': ('South African Rand', 'R'),
  'ZMW': ('Zambian Kwacha', 'ZK'),
  'ZWG': ('Zimbabwe Gold', 'ZiG'),
};
