# Generated by Django 6.0.1 on 2026-02-15 07:22

from django.db import migrations

# Columns that has user_id and need RLS
RLS_TABLES = [
    'refresh_tokens',
    'user_preferences',
    'users'
]

def enable_rls(apps, schema_editor):
    # Enable RLS for tables that have user_id
    for table in RLS_TABLES:
        schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

        # Force RLS even for table owners (!important)
        schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

        # Policy: users can only see their own rows
        schema_editor.execute(f"""
            CREATE POLICY user_isolation_policy ON {table} USING (user_id = current_setting('app.current_user_id', true)::int);
        """)

def disable_rls(apps, schema_editor):
    # Disable RLS for tables that have user_id
    for table in RLS_TABLES:
        schema_editor.execute(f"DROP POLICY IF EXISTS user_isolation_policy ON {table}")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls)
    ]
