# Generated by Django 6.0.1 on 2026-02-15 07:22

from django.db import connection, migrations

# Tables that have a user_id column and need RLS
RLS_TABLES = [
    'refresh_tokens',
    'sub_currencies',
    'user_preferences',
]

def enable_rls(apps, schema_editor):
    # RLS is PostgreSQL-only; skip for SQLite (used in tests)
    if connection.vendor != 'postgresql':
        return

    for table in RLS_TABLES:
        schema_editor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        schema_editor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        schema_editor.execute(f"""
            CREATE POLICY user_isolation_policy ON {table}
                USING (user_id = current_setting('app.current_user_id', true)::int);
        """)

def disable_rls(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return

    for table in RLS_TABLES:
        schema_editor.execute(f"DROP POLICY IF EXISTS user_isolation_policy ON {table}")
        schema_editor.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls)
    ]
