# Generated by Django 6.0.1 on 2026-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_enable_rls_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CAD', 'CAD'), ('INR', 'INR')], default='USD', max_length=3),
        ),
    ]
